### ISSUE TITLE
v1.x - Senden Button bei minimiertem Fenster nicht mehr anklickbar

### ISSUE THREAD

**Issue by mbrain** [zarat/IM#13]
Das Textfeald wächst über das Fenster hinaus und man kann nicht mehr chatten wenn man zu viele PMs in Abwesenheit (bei minimiertem Fenster) bekommt.

**Comment by zarat** [comment]
Habs mir gerade angesehen und das scheinst ein ernsthaftes Problem zu sein. Ich hab den FocusListener https://github.com/zarat/IM/issues/12 nämlich in 1.0 und 1.1 miteingebaut und viele der Variablen heissen jetzt anders :S

**Comment by zarat** [comment]
In 0.3 hab ich ein StyledDocument aber den Fehler nicht! 0.2 hab ich mit JTextArea und noch nicht probiert. Mache ich heute noch.

**Comment by mbrain** [comment]
Hab ich gerade gesehen, werd ich dann wohl auch so machen.
